[lifecycle]

setup_script = "amika-scripts/setup.sh"

[services.frontend]
port = 4102
url_scheme = "https"

[env]
MY_VAR = "my-var"

# This secret must be set. Either do it via the UI or from CLI
MY_SECRET = { secret = "my-secret" }

VITE_FRONTEND_URL = { service = "frontend", field = "url" }
VITE_FRONTEND_PORT = { service = "frontend", field = "port" }
